#! /bin/bash


#echo Generating 10 million entries. This might take a while
#echo Generating dataset
test-kdtree-Generator 100000 0 > d
awk '{if ($1 == 1) print $0}' < d > data
awk '{if ($1 == 2) print $0}' < d > queries
rm -rf d

echo Creating new R-Tree
time test-kdtree-KDTreeBulkLoad data tree 100 0.9

echo Querying R-Tree
time test-kdtree-KDTreeQuery queries tree intersection > res
cat data queries > .t

echo Running exhaustive search
time test-kdtree-Exhaustive .t intersection > res2

echo Comparing results
sort -n res > a
sort -n res2 > b
if diff a b
then echo "Same results with exhaustive search. Everything seems fine."
else echo "PROBLEM! We got different results from exhaustive search!"
fi
echo Results: `wc -l a`
rm -rf a b res res2 .t tree.*
